# Generated by Django 4.0.6 on 2022-07-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnirbanBhattacharyaWebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Description', models.CharField(default='', max_length=200)),
                ('DateAdded', models.CharField(default='', max_length=20)),
                ('Image', models.CharField(default='', max_length=300)),
                ('Slug', models.CharField(default='', max_length=300)),
                ('Category', models.CharField(choices=[('Coding', 'Coding'), ('Python', 'Python'), ('Business', 'Business'), ('Stock Market', 'Stock Market')], max_length=60)),
                ('Post', models.TextField(default='', max_length=10000)),
                ('Author', models.CharField(default='', max_length=90)),
                ('Views', models.CharField(default='', max_length=400)),
                ('Likes', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
