# Generated by Django 4.0.6 on 2022-07-12 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AnirbanBhattacharyaWebsite', '0003_alter_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Likes',
        ),
        migrations.AddField(
            model_name='blog',
            name='Likes',
            field=models.ManyToManyField(related_name='UserLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
