# Generated by Django 4.0.6 on 2022-07-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnirbanBhattacharyaWebsite', '0006_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Likes',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
