# Generated by Django 4.0.6 on 2022-07-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnirbanBhattacharyaWebsite', '0008_alter_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Views',
            field=models.CharField(default='0', max_length=400),
        ),
    ]
