# Generated by Django 4.0.6 on 2022-08-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnirbanBhattacharyaWebsite', '0011_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='hired',
            name='Budget',
            field=models.CharField(default='', max_length=50),
        ),
    ]
