# Generated by Django 4.0.6 on 2022-11-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnirbanBhattacharyaWebsite', '0013_alter_hired_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hired',
            name='Budget',
            field=models.IntegerField(default=''),
        ),
    ]
