# Generated by Django 4.1.3 on 2022-12-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0014_alter_hired_budget"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hired",
        ),
    ]
