# Generated by Django 4.1.3 on 2022-12-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0015_delete_hired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Description",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="blog",
            name="Post",
            field=models.TextField(default="", max_length=100000),
        ),
    ]
