# Generated by Django 4.1.3 on 2022-12-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0016_alter_blog_description_alter_blog_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Description",
            field=models.CharField(default="", max_length=150),
        ),
    ]
