# Generated by Django 4.1.3 on 2022-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0017_alter_blog_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.CharField(default="", max_length=60)),
            ],
        ),
    ]
