# Generated by Django 4.1.3 on 2022-12-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0018_newsmail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="Message",
            field=models.TextField(default="", max_length=10000),
        ),
    ]
