# Generated by Django 5.0.1 on 2024-02-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0020_photos"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Photos",
            new_name="Photo",
        ),
    ]
