# Generated by Django 5.0.1 on 2024-02-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0022_alter_photo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="Name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="photo",
            name="Image",
            field=models.ImageField(upload_to="PersonalPhotos"),
        ),
    ]
