# Generated by Django 5.0.1 on 2024-02-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0023_photo_name_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="Name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
