# Generated by Django 5.0.1 on 2024-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0024_alter_photo_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="Keywords",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
