# Generated by Django 5.0.1 on 2024-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0025_blog_keywords"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="", max_length=200)),
                ("Description", models.CharField(default="", max_length=150)),
                ("Keywords", models.CharField(default="", max_length=2000)),
                ("DateAdded", models.CharField(default="", max_length=20)),
                ("Image", models.CharField(default="", max_length=300)),
                ("Slug", models.CharField(default="", max_length=300)),
                (
                    "Category",
                    models.CharField(
                        choices=[
                            ("Top Trends", "Top Trends"),
                            ("Stock Market", "Stock Market"),
                            ("Shark Tank India", "Shark Tank India"),
                            ("Technology", "Technology"),
                            ("Good Reads", "Good Reads"),
                            ("Python", "Python"),
                            ("Business News", "Business News"),
                        ],
                        max_length=60,
                    ),
                ),
                ("Post", models.TextField(default="", max_length=100000)),
                ("Author", models.CharField(default="", max_length=90)),
                ("Views", models.CharField(default="0", max_length=400)),
                ("Likes", models.CharField(default="0", max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="IP",
        ),
    ]
