# Generated by Django 5.0.1 on 2024-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0026_featuredblog_delete_blog_delete_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredblog",
            name="Category",
            field=models.CharField(
                choices=[
                    ("Top Trends", "Top Trends"),
                    ("Failure Chronicles", "Failure Chronicles"),
                    ("Entertainment", "Entertainment"),
                    ("Shark Tank India", "Shark Tank India"),
                    ("Technology", "Technology"),
                    ("Good Reads", "Good Reads"),
                    ("Python", "Python"),
                    ("Business News", "Business News"),
                ],
                max_length=60,
            ),
        ),
    ]
