# Generated by Django 5.0.1 on 2024-05-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0027_alter_featuredblog_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalVeri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("OTP", models.IntegerField()),
            ],
        ),
    ]
