# Generated by Django 5.0.1 on 2024-05-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0028_galveri"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GalVeri",
            new_name="GalVerifi",
        ),
    ]
