# Generated by Django 5.0.1 on 2024-05-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0029_rename_galveri_galverifi"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsMail",
        ),
    ]
