# Generated by Django 5.0.1 on 2024-05-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0030_delete_newsmail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galverifi",
            name="OTP",
            field=models.CharField(max_length=10),
        ),
    ]
