# Generated by Django 5.0.1 on 2024-07-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0031_alter_galverifi_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="Type",
            field=models.CharField(default="p", max_length=20),
        ),
    ]
