# Generated by Django 5.0.1 on 2024-07-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0032_photo_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="Image",
            field=models.FileField(upload_to="PersonalPhotos"),
        ),
    ]
