# Generated by Django 5.0.1 on 2024-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnirbanBhattacharyaWebsite", "0033_alter_photo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="galverifi",
            name="Perma",
            field=models.BooleanField(default=False),
        ),
    ]
