# Generated by Django 5.0.6 on 2024-10-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnirbanBhattacharyaWebsite', '0034_galverifi_perma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredblog',
            name='Category',
            field=models.CharField(choices=[('Top Trends', 'Top Trends'), ('Failure Chronicles', 'Failure Chronicles'), ('Entertainment', 'Entertainment'), ('Shark Tank India', 'Shark Tank India'), ('Technology', 'Technology'), ('Good Reads', 'Good Reads'), ('Python', 'Python'), ('Business News', 'Business News'), ('Entrepreneurship', 'Entrepreneurship')], max_length=60),
        ),
    ]
